name: Build Faiss Wheels

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to build wheels for (e.g.: 3.10, 3.12)'
        required: true
        type: string
        default: '3.12'

jobs:
  job1:
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python ${{ github.event.inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ github.event.inputs.python-version }}
          cache: 'pip'
          pip-install: -r requirements.txt
          
      - name: Find mkl
        continue-on-error: true
        run: |
          python spam.py
      
      - name: Find mkl with pwsh
        run: |
          Get-ChildItem -Recurse -Filter mkl_avx2.2.dll $(python -m site --user-base) -ErrorAction SilentlyContinue
          Get-ChildItem -Recurse -Filter mkl_avx2.2.dll $(python -m site --user-site) -ErrorAction SilentlyContinue
          Get-ChildItem -Recurse -Filter mkl_avx2.2.dll $(python -c "import sys; print(sys.prefix)") -ErrorAction SilentlyContinue

      - name: Enable longpaths in git
        if: ${{ runner.os == 'Windows' }}
        run: git config --global core.longpaths true

      - name: Build Faiss Wheels
        run: |
          Push-Location faiss\build\faiss\python
          python -m build --wheel --no-isolation
          ls dist\
          Pop-Location
      
      - name: Upload Faiss Wheels
        uses: actions/upload-artifact@v6
        with:
          name: faiss-wheels
          path: faiss\build\faiss\python\dist\*.whl
          compression-level: 0
      

